program:
  - name: source_flow
    type: VARIABLE
    expression: source_flow = 0.01
  
  - name: mv
    type: LIST_WAVE
    init_args:
      wave_list:
        - [0, 1000]
        - [50, 1000]
        - [100, 1000]
    display_args: []
    expression: mv.execute()
  - name: valve_1
    type: VALVE
    init_args:
      full_travel_time: 10
    display_args: [ "outlet_flow[0.2]", "current_opening[100]", "target_opening[100]"]
    expression: valve_1.execute(target_opening=mv.out, inlet_flow=source_flow)
  - name: tank_1
    type: CYLINDRICAL_TANK
    init_args: {}
    display_args: ["level[2]"]
    expression: tank_1.execute(inlet_flow=valve_1.outlet_flow)
  - name: tank_2
    type: CYLINDRICAL_TANK
    init_args: {}
    display_args: ["level[2]"]
    expression: tank_2.execute(inlet_flow=tank_1.outlet_flow)
  - name: M_DV1
    type: RANDOM
    init_args:
      L: 0.0
      H: 100.0
      max_step: 3.0
    display_args: ["out[100]"]
    expression: M_DV1.execute()
  - name: M_MV3
    type: VARIABLE
    expression: M_MV3 = valve_1.current_opening
    display_args:
      - M_MV3