import type { StatusResponse, MetaResponse, DisplayVar } from '../types'

// Go bindings are auto-generated by Wails in ../wailsjs/go/bindings/DebugBinding
// These TypeScript wrappers parse the JSON strings returned by Go.

async function callGo<T>(fn: () => Promise<string>): Promise<T | null> {
  try {
    const raw = await fn()
    if (!raw || raw === '{}' || raw === '[]') return null
    return JSON.parse(raw) as T
  } catch {
    return null
  }
}

export async function connect(url: string): Promise<string | null> {
  try {
    const { Connect } = await import('../../wailsjs/go/bindings/DebugBinding')
    const name = await Connect(url)
    return name || null
  } catch {
    return null
  }
}

export async function disconnect(): Promise<void> {
  try {
    const { Disconnect } = await import('../../wailsjs/go/bindings/DebugBinding')
    await Disconnect()
  } catch {
    // ignore
  }
}

export async function getStatus(): Promise<StatusResponse | null> {
  const { GetStatus } = await import('../../wailsjs/go/bindings/DebugBinding')
  return callGo<StatusResponse>(GetStatus)
}

export async function getMeta(): Promise<MetaResponse | null> {
  const { GetMeta } = await import('../../wailsjs/go/bindings/DebugBinding')
  return callGo<MetaResponse>(GetMeta)
}

export async function setParam(
  name: string,
  param: string,
  value: number
): Promise<void> {
  try {
    const { SetParam } = await import('../../wailsjs/go/bindings/DebugBinding')
    await SetParam(name, param, value)
  } catch {
    // ignore
  }
}

export async function override(tag: string, value: number): Promise<void> {
  try {
    const { Override } = await import('../../wailsjs/go/bindings/DebugBinding')
    await Override(tag, value)
  } catch {
    // ignore
  }
}

export async function exportCsv(path: string): Promise<string | null> {
  try {
    const { ExportCsv } = await import('../../wailsjs/go/bindings/DebugBinding')
    return await ExportCsv(path)
  } catch {
    return null
  }
}

export async function getDisplayVariables(): Promise<DisplayVar[]> {
  try {
    const { GetDisplayVariables } = await import(
      '../../wailsjs/go/bindings/DebugBinding'
    )
    const raw = await GetDisplayVariables()
    if (!raw || raw === '[]') return []
    return JSON.parse(raw) as DisplayVar[]
  } catch {
    return []
  }
}

export async function getSnapshotHistory(): Promise<
  Record<string, number | boolean>[]
> {
  try {
    const { GetSnapshotHistory } = await import(
      '../../wailsjs/go/bindings/DebugBinding'
    )
    const raw = await GetSnapshotHistory()
    if (!raw || raw === '[]') return []
    return JSON.parse(raw)
  } catch {
    return []
  }
}
