// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {context} from '../models';

export function ListDataSources():Promise<Array<bindings.DataSourceDTO>>;

export function ListTags(arg1:bindings.ListTagsRequestDTO):Promise<Array<bindings.TagDTO>>;

export function ReadHistory(arg1:bindings.ReadHistoryRequestDTO):Promise<Array<bindings.HistoryRowDTO>>;

export function ReadRealtime(arg1:Array<string>):Promise<Array<bindings.RTValueDTO>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function WriteValues(arg1:bindings.WriteRequestDTO):Promise<bindings.WriteResultDTO>;
