// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListDataSources() {
  return window['go']['bindings']['RWBinding']['ListDataSources']();
}

export function ListTags(arg1) {
  return window['go']['bindings']['RWBinding']['ListTags'](arg1);
}

export function ReadHistory(arg1) {
  return window['go']['bindings']['RWBinding']['ReadHistory'](arg1);
}

export function ReadRealtime(arg1) {
  return window['go']['bindings']['RWBinding']['ReadRealtime'](arg1);
}

export function SetContext(arg1) {
  return window['go']['bindings']['RWBinding']['SetContext'](arg1);
}

export function WriteValues(arg1) {
  return window['go']['bindings']['RWBinding']['WriteValues'](arg1);
}
