// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Login(arg1) {
  return window['go']['bindings']['SessionBinding']['Login'](arg1);
}

export function Logout() {
  return window['go']['bindings']['SessionBinding']['Logout']();
}

export function SetContext(arg1) {
  return window['go']['bindings']['SessionBinding']['SetContext'](arg1);
}

export function Status() {
  return window['go']['bindings']['SessionBinding']['Status']();
}
