// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CompareAlgorithms(arg1:Array<main.CSVRecord>):Promise<main.CompareResult>;

export function Connect(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ConnectResult>;

export function ExportAlgorithms(arg1:string):Promise<main.ConnectResult>;

export function GetPublishedAlgorithms():Promise<main.PublishedAlgosResult>;

export function IsConnected():Promise<boolean>;

export function LoadCSVFile(arg1:string):Promise<main.LoadCSVResult>;

export function PickCSVFile():Promise<string>;

export function PickDirectory():Promise<string>;

export function SaveCSVFile(arg1:string):Promise<string>;

export function StartPublish(arg1:Array<main.PublishItem>,arg2:number):Promise<main.PublishStartResult>;

export function StartRepublish():Promise<main.PublishStartResult>;

export function StartSync(arg1:string,arg2:boolean):Promise<main.SyncStartResult>;
