cycle: 1000
namespace_index: 1
nodes:
- change: true
  count: 1
  name: mock_Boolean_r_
  type: Boolean
  writable: false
- change: false
  count: 1
  default: false
  name: mock_Boolean_w_
  type: Boolean
  writable: true
- change: true
  count: 1
  name: mock_SByte_r_
  type: SByte
  writable: false
- change: false
  count: 1
  default: 0
  name: mock_SByte_w_
  type: SByte
  writable: true
- change: true
  count: 1
  name: mock_Byte_r_
  type: Byte
  writable: false
- change: false
  count: 1
  default: 0
  name: mock_Byte_w_
  type: Byte
  writable: true
- change: true
  count: 1
  name: mock_Int16_r_
  type: Int16
  writable: false
- change: false
  count: 1
  default: 0
  name: mock_Int16_w_
  type: Int16
  writable: true
- change: true
  count: 1
  name: mock_UInt16_r_
  type: UInt16
  writable: false
- change: false
  count: 1
  default: 0
  name: mock_UInt16_w_
  type: UInt16
  writable: true
- change: true
  count: 1
  name: mock_Int32_r_
  type: Int32
  writable: false
- change: false
  count: 1
  default: 0
  name: mock_Int32_w_
  type: Int32
  writable: true
- change: true
  count: 1
  name: mock_UInt32_r_
  type: UInt32
  writable: false
- change: false
  count: 1
  default: 0
  name: mock_UInt32_w_
  type: UInt32
  writable: true
- change: true
  count: 1
  name: mock_Int64_r_
  type: Int64
  writable: false
- change: false
  count: 1
  default: 0
  name: mock_Int64_w_
  type: Int64
  writable: true
- change: true
  count: 1
  name: mock_UInt64_r_
  type: UInt64
  writable: false
- change: false
  count: 1
  default: 0
  name: mock_UInt64_w_
  type: UInt64
  writable: true
- change: true
  count: 1
  name: mock_Float_r_
  type: Float
  writable: false
- change: false
  count: 1
  default: 0.0
  name: mock_Float_w_
  type: Float
  writable: true
- change: true
  count: 1
  name: mock_Double_r_
  type: Double
  writable: false
- change: false
  count: 1
  default: 0.0
  name: mock_Double_w_
  type: Double
  writable: true
- change: true
  count: 1
  name: mock_String_r_
  type: String
  writable: false
- change: false
  count: 1
  default: ''
  name: mock_String_w_
  type: String
  writable: true
- change: true
  count: 1
  name: mock_DateTime_r_
  type: DateTime
  writable: false
- change: false
  count: 1
  default: '2025-01-01T00:00:00Z'
  name: mock_DateTime_w_
  type: DateTime
  writable: true
- change: true
  count: 1
  default: 0
  name: mock_hb
  type: Int32
  writable: false
port: 18960
server: 0.0.0.0
