// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {batch} from '../models';
import {context} from '../models';

export function ClearAllScores():Promise<batch.ClearAllResult>;

export function GetEvalConfig():Promise<batch.EvalConfig>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateEvalConfig(arg1:number,arg2:number,arg3:number,arg4:number):Promise<batch.UpdateResult>;
