// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEvalConfig() {
  return window['go']['bindings']['BatchBinding']['GetEvalConfig']();
}

export function SetContext(arg1) {
  return window['go']['bindings']['BatchBinding']['SetContext'](arg1);
}

export function UpdateEvalConfig(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['BatchBinding']['UpdateEvalConfig'](arg1, arg2, arg3, arg4);
}
