// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {monitor} from '../models';
import {context} from '../models';

export function ConfirmAbnormal(arg1:string):Promise<void>;

export function GetMonitorSnapshot():Promise<monitor.Snapshot>;

export function ScanMonitor():Promise<monitor.Report>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartMonitor():Promise<void>;

export function StopMonitor():Promise<void>;
