// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMonitorSnapshot() {
  return window['go']['bindings']['MonitorBinding']['GetMonitorSnapshot']();
}

export function ScanMonitor() {
  return window['go']['bindings']['MonitorBinding']['ScanMonitor']();
}

export function SetContext(arg1) {
  return window['go']['bindings']['MonitorBinding']['SetContext'](arg1);
}

export function StartMonitor() {
  return window['go']['bindings']['MonitorBinding']['StartMonitor']();
}

export function StopMonitor() {
  return window['go']['bindings']['MonitorBinding']['StopMonitor']();
}
