// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupTenant(arg1) {
  return window['go']['bindings']['PersonalBinding']['CleanupTenant'](arg1);
}

export function GetPersonalList() {
  return window['go']['bindings']['PersonalBinding']['GetPersonalList']();
}

export function GetTenantDetail(arg1) {
  return window['go']['bindings']['PersonalBinding']['GetTenantDetail'](arg1);
}

export function SetContext(arg1) {
  return window['go']['bindings']['PersonalBinding']['SetContext'](arg1);
}
