// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {personal} from '../models';
import {context} from '../models';

export function CleanupTenant(arg1:string):Promise<personal.CleanupResult>;

export function GetPersonalList():Promise<Array<personal.Row>>;

export function GetTenantDetail(arg1:string):Promise<personal.Detail>;

export function SetContext(arg1:context.Context):Promise<void>;
