// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ranking} from '../models';
import {context} from '../models';

export function GetRanking():Promise<Array<ranking.Item>>;

export function SetContext(arg1:context.Context):Promise<void>;
