// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {task} from '../models';
import {context} from '../models';

export function GetTeamTaskStats():Promise<Array<task.TeamTaskStats>>;

export function SetContext(arg1:context.Context):Promise<void>;
