// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTeamTaskStats() {
  return window['go']['bindings']['TaskBinding']['GetTeamTaskStats']();
}

export function SetContext(arg1) {
  return window['go']['bindings']['TaskBinding']['SetContext'](arg1);
}
