// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {team} from '../models';
import {context} from '../models';

export function GetTeams():Promise<Array<team.Team>>;

export function SetContext(arg1:context.Context):Promise<void>;
