// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTeams() {
  return window['go']['bindings']['TeamBinding']['GetTeams']();
}

export function SetContext(arg1) {
  return window['go']['bindings']['TeamBinding']['SetContext'](arg1);
}
