import type { DraftConfig, SelectedObjectId } from '../types'

// 每个对象的中文名与组件类型
export interface SecondOrderTankObjectMeta {
  id: SelectedObjectId
  displayName: string
  componentType: string
  // 高级字段前缀（用于折叠）
  advancedFieldPrefixes: string[]
  // 推荐趋势位号
  trendTags: string[]
}

export const SECOND_ORDER_TANK_OBJECTS: SecondOrderTankObjectMeta[] = [
  {
    id: 'source_flow',
    displayName: '水源',
    componentType: 'Variable',
    advancedFieldPrefixes: [],
    trendTags: ['source_flow'],
  },
  {
    id: 'valve_1',
    displayName: '调节阀',
    componentType: 'VALVE',
    advancedFieldPrefixes: ['valve.minOpening', 'valve.maxOpening', 'valve.flowCoefficient'],
    trendTags: ['valve_1.current_opening', 'valve_1.target_opening'],
  },
  {
    id: 'tank_1',
    displayName: '上游水箱',
    componentType: 'CYLINDRICAL_TANK',
    advancedFieldPrefixes: ['tank1.outletArea'],
    trendTags: ['tank_1.level'],
  },
  {
    id: 'tank_2',
    displayName: '下游水箱',
    componentType: 'CYLINDRICAL_TANK',
    advancedFieldPrefixes: ['tank2.outletArea'],
    trendTags: ['tank_2.level', 'pid2.SV'],
  },
  {
    id: 'lt_201',
    displayName: '液位测量',
    componentType: 'LT',
    advancedFieldPrefixes: [],
    trendTags: [],
  },
  {
    id: 'pid2',
    displayName: '液位控制器',
    componentType: 'PID',
    advancedFieldPrefixes: [
      'pid.KD',
      'pid.SWPN',
      'pid.SVSCL', 'pid.SVSCH', 'pid.SVL', 'pid.SVH',
      'pid.MVSCL', 'pid.MVSCH', 'pid.MVL', 'pid.MVH',
    ],
    trendTags: ['pid2.PV', 'pid2.SV', 'pid2.MV', 'pid2.MODE'],
  },
]

// 字段显示元数据
export interface FieldDisplayMeta {
  path: string
  label: string
  yamlPath: string // 原始 YAML 参数路径
  unit: string
  displayUnit: string // 显示单位（如果与 unit 不同则需要换算）
  effectiveOn: 'restart' | 'realtime'
  appliesTo: SelectedObjectId | 'all'
  // 换算函数（从 draft 原始值转为显示值）
  toDisplay?: (value: number) => number
  // 换算函数（从显示值转为 draft 原始值）
  fromDisplay?: (value: number) => number
  // 是否只读
  readOnly?: boolean
  // 合法范围；跨字段约束必须从当前 draft 动态生成。
  range?: string | ((draft: DraftConfig) => string)
  // 帮助文本
  helpText?: string
}

export const FIELD_DISPLAY: FieldDisplayMeta[] = [
  {
    path: 'cycleTime',
    label: '控制周期',
    yamlPath: 'clock.cycle_time',
    unit: 's',
    displayUnit: 's',
    effectiveOn: 'restart',
    appliesTo: 'all',
    range: '> 0',
    helpText: '每个控制周期的时长',
  },
  {
    path: 'sourceFlow',
    label: '水源流量',
    yamlPath: 'program.source_flow.value',
    unit: 'm³/s',
    displayUnit: 'L/min',
    effectiveOn: 'restart',
    appliesTo: 'source_flow',
    toDisplay: (v) => v * 60_000,
    fromDisplay: (v) => v / 60_000,
    range: '≥ 0',
    helpText: '恒定水源供给流量',
  },
  {
    path: 'valve.fullTravelTime',
    label: '满行程时间',
    yamlPath: 'program.valve_1.params.full_travel_time',
    unit: 's',
    displayUnit: 's',
    effectiveOn: 'restart',
    appliesTo: 'valve_1',
    range: '≥ 0',
    helpText: '阀门从 0% 到 100% 的全行程时间',
  },
  {
    path: 'valve.initialOpening',
    label: '初始开度',
    yamlPath: 'program.valve_1.params.initial_opening',
    unit: '%',
    displayUnit: '%',
    effectiveOn: 'restart',
    appliesTo: 'valve_1',
    range: (draft) => `[${draft.valve.minOpening}, ${draft.valve.maxOpening}]`,
    helpText: '阀门在仿真启动时的初始开度',
  },
  {
    path: 'valve.flowCoefficient',
    label: '流量系数',
    yamlPath: 'program.valve_1.params.flow_coefficient',
    unit: '—',
    displayUnit: '—',
    effectiveOn: 'restart',
    appliesTo: 'valve_1',
    range: '≥ 0',
    helpText: '阀门流量系数，用于计算实际流量',
  },
  {
    path: 'valve.minOpening',
    label: '最小开度',
    yamlPath: 'program.valve_1.params.min_opening',
    unit: '%',
    displayUnit: '%',
    effectiveOn: 'restart',
    appliesTo: 'valve_1',
    range: (draft) => `[0, 100] 且 < ${draft.valve.maxOpening}`,
    helpText: '阀门允许的最小开度限制',
  },
  {
    path: 'valve.maxOpening',
    label: '最大开度',
    yamlPath: 'program.valve_1.params.max_opening',
    unit: '%',
    displayUnit: '%',
    effectiveOn: 'restart',
    appliesTo: 'valve_1',
    range: (draft) => `[0, 100] 且 > ${draft.valve.minOpening}`,
    helpText: '阀门允许的最大开度限制',
  },
  {
    path: 'tank1.height',
    label: '高度',
    yamlPath: 'program.tank_1.params.height',
    unit: 'm',
    displayUnit: 'm',
    effectiveOn: 'restart',
    appliesTo: 'tank_1',
    range: '> 0',
    helpText: '水箱的物理高度',
  },
  {
    path: 'tank1.radius',
    label: '半径',
    yamlPath: 'program.tank_1.params.radius',
    unit: 'm',
    displayUnit: 'm',
    effectiveOn: 'restart',
    appliesTo: 'tank_1',
    range: '> 0',
    helpText: '水箱的内半径',
  },
  {
    path: 'tank1.outletArea',
    label: '出口直径',
    yamlPath: 'program.tank_1.params.outlet_area',
    unit: 'm²',
    displayUnit: 'mm',
    effectiveOn: 'restart',
    appliesTo: 'tank_1',
    toDisplay: (v) => 2 * Math.sqrt(v / Math.PI) * 1_000,
    fromDisplay: (v) => {
      const m = v / 1_000
      return Math.PI * m * m / 4
    },
    range: '> 0',
    helpText: '出口等效直径',
  },
  {
    path: 'tank1.initialLevel',
    label: '初始液位',
    yamlPath: 'program.tank_1.params.initial_level',
    unit: 'm',
    displayUnit: 'm',
    effectiveOn: 'restart',
    appliesTo: 'tank_1',
    range: (draft) => `[0, ${draft.tank1.height}]`,
    helpText: '仿真启动时的液位高度',
  },
  {
    path: 'tank1.volume',
    label: '容量',
    yamlPath: '',
    unit: 'L',
    displayUnit: 'L',
    effectiveOn: 'restart',
    appliesTo: 'tank_1',
    readOnly: true,
    helpText: '水箱总容量（派生值）',
  },
  {
    path: 'tank2.height',
    label: '高度',
    yamlPath: 'program.tank_2.params.height',
    unit: 'm',
    displayUnit: 'm',
    effectiveOn: 'restart',
    appliesTo: 'tank_2',
    range: '> 0',
    helpText: '水箱的物理高度',
  },
  {
    path: 'tank2.radius',
    label: '半径',
    yamlPath: 'program.tank_2.params.radius',
    unit: 'm',
    displayUnit: 'm',
    effectiveOn: 'restart',
    appliesTo: 'tank_2',
    range: '> 0',
    helpText: '水箱的内半径',
  },
  {
    path: 'tank2.outletArea',
    label: '出口直径',
    yamlPath: 'program.tank_2.params.outlet_area',
    unit: 'm²',
    displayUnit: 'mm',
    effectiveOn: 'restart',
    appliesTo: 'tank_2',
    toDisplay: (v) => 2 * Math.sqrt(v / Math.PI) * 1_000,
    fromDisplay: (v) => {
      const m = v / 1_000
      return Math.PI * m * m / 4
    },
    range: '> 0',
    helpText: '出口等效直径',
  },
  {
    path: 'tank2.initialLevel',
    label: '初始液位',
    yamlPath: 'program.tank_2.params.initial_level',
    unit: 'm',
    displayUnit: 'm',
    effectiveOn: 'restart',
    appliesTo: 'tank_2',
    range: (draft) => `[0, ${draft.tank2.height}]`,
    helpText: '仿真启动时的液位高度',
  },
  {
    path: 'tank2.volume',
    label: '容量',
    yamlPath: '',
    unit: 'L',
    displayUnit: 'L',
    effectiveOn: 'restart',
    appliesTo: 'tank_2',
    readOnly: true,
    helpText: '水箱总容量（派生值）',
  },
  {
    path: 'pid.PB',
    label: 'PB',
    yamlPath: 'program.pid2.params.PB',
    unit: '',
    displayUnit: '',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: '> 0',
    helpText: '比例度（Proportional Band）',
  },
  {
    path: 'pid.TI',
    label: 'TI',
    yamlPath: 'program.pid2.params.TI',
    unit: 's',
    displayUnit: 's',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: '≥ 0',
    helpText: '积分时间',
  },
  {
    path: 'pid.TD',
    label: 'TD',
    yamlPath: 'program.pid2.params.TD',
    unit: 's',
    displayUnit: 's',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: '≥ 0',
    helpText: '微分时间',
  },
  {
    path: 'pid.KD',
    label: 'KD',
    yamlPath: 'program.pid2.params.KD',
    unit: '',
    displayUnit: '',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: '> 0',
    helpText: '微分增益',
  },
  {
    path: 'pid.SV',
    label: 'SV',
    yamlPath: 'program.pid2.params.SV',
    unit: 'm',
    displayUnit: 'm',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: (draft) => `[${draft.pid.SVL}, ${draft.pid.SVH}]`,
    helpText: '设定值（Setpoint）',
  },
  {
    path: 'pid.MV',
    label: 'MV',
    yamlPath: 'program.pid2.params.MV',
    unit: '%',
    displayUnit: '%',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: (draft) => `[${draft.pid.MVL}, ${draft.pid.MVH}]`,
    helpText: '操作输出（Manipulated Variable）',
  },
  {
    path: 'pid.MODE',
    label: 'MODE',
    yamlPath: 'program.pid2.params.MODE',
    unit: '',
    displayUnit: '',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: '整数 1～8',
    helpText: '控制模式（4=MAN, 5=AUTO, 6=CAS）',
  },
  {
    path: 'pid.SWPN',
    label: 'SWPN',
    yamlPath: 'program.pid2.params.SWPN',
    unit: '',
    displayUnit: '',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: '0 或 1',
    helpText: '作用方向（1=反作用, 0=正作用）',
  },
  {
    path: 'pid.SVSCL',
    label: 'SVSCL',
    yamlPath: 'program.pid2.params.SVSCL',
    unit: 'm',
    displayUnit: 'm',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: (draft) => `< SVSCH (${draft.pid.SVSCH})`,
    helpText: 'SV 量程下限',
  },
  {
    path: 'pid.SVSCH',
    label: 'SVSCH',
    yamlPath: 'program.pid2.params.SVSCH',
    unit: 'm',
    displayUnit: 'm',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: (draft) => `> SVSCL (${draft.pid.SVSCL})，且 ≤ Tank 2 高度 (${draft.tank2.height})`,
    helpText: 'SV 量程上限',
  },
  {
    path: 'pid.SVL',
    label: 'SVL',
    yamlPath: 'program.pid2.params.SVL',
    unit: 'm',
    displayUnit: 'm',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: (draft) => `[SVSCL (${draft.pid.SVSCL}), SVH (${draft.pid.SVH})]`,
    helpText: 'SV 操作下限',
  },
  {
    path: 'pid.SVH',
    label: 'SVH',
    yamlPath: 'program.pid2.params.SVH',
    unit: 'm',
    displayUnit: 'm',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: (draft) => `[SVL (${draft.pid.SVL}), SVSCH (${draft.pid.SVSCH})]，且 ≤ Tank 2 高度 (${draft.tank2.height})`,
    helpText: 'SV 操作上限',
  },
  {
    path: 'pid.MVSCL',
    label: 'MVSCL',
    yamlPath: 'program.pid2.params.MVSCL',
    unit: '%',
    displayUnit: '%',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: (draft) => `< MVSCH (${draft.pid.MVSCH})`,
    helpText: 'MV 量程下限',
  },
  {
    path: 'pid.MVSCH',
    label: 'MVSCH',
    yamlPath: 'program.pid2.params.MVSCH',
    unit: '%',
    displayUnit: '%',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: (draft) => `> MVSCL (${draft.pid.MVSCL})`,
    helpText: 'MV 量程上限',
  },
  {
    path: 'pid.MVL',
    label: 'MVL',
    yamlPath: 'program.pid2.params.MVL',
    unit: '%',
    displayUnit: '%',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: (draft) => `[MVSCL (${draft.pid.MVSCL}), MVH (${draft.pid.MVH})]`,
    helpText: 'MV 下限',
  },
  {
    path: 'pid.MVH',
    label: 'MVH',
    yamlPath: 'program.pid2.params.MVH',
    unit: '%',
    displayUnit: '%',
    effectiveOn: 'realtime',
    appliesTo: 'pid2',
    range: (draft) => `[MVL (${draft.pid.MVL}), MVSCH (${draft.pid.MVSCH})]`,
    helpText: 'MV 上限',
  },
]

// LT-201 信号绑定（虚拟仪表）
export const LT_201_BINDING = {
  sourceTag: 'tank_2.level',
  targetTag: 'pid2.PV',
  description: '将 tank_2 液位信号传递给 pid2 作为过程变量',
}
