// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';

export function List():Promise<Array<config.ComponentMeta>>;

export function SetContext(arg1:context.Context):Promise<void>;
