// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';

export function ExportYAML(arg1:config.CanvasState,arg2:string):Promise<void>;

export function ImportYAML(arg1:string):Promise<config.CanvasState>;

export function LoadCanvas(arg1:string):Promise<config.CanvasState>;

export function SaveCanvas(arg1:config.CanvasState,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Validate(arg1:config.CanvasState):Promise<config.ValidationResult>;
