// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportYAML(arg1, arg2) {
  return window['go']['bindings']['ConfigBinding']['ExportYAML'](arg1, arg2);
}

export function ImportYAML(arg1) {
  return window['go']['bindings']['ConfigBinding']['ImportYAML'](arg1);
}

export function LoadCanvas(arg1) {
  return window['go']['bindings']['ConfigBinding']['LoadCanvas'](arg1);
}

export function SaveCanvas(arg1, arg2) {
  return window['go']['bindings']['ConfigBinding']['SaveCanvas'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['bindings']['ConfigBinding']['SetContext'](arg1);
}

export function Validate(arg1) {
  return window['go']['bindings']['ConfigBinding']['Validate'](arg1);
}
