// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cleanup() {
  return window['go']['bindings']['RealtimeRuntimeBinding']['Cleanup']();
}

export function GetProjectRevision(arg1) {
  return window['go']['bindings']['RealtimeRuntimeBinding']['GetProjectRevision'](arg1);
}

export function GetSession() {
  return window['go']['bindings']['RealtimeRuntimeBinding']['GetSession']();
}

export function SetContext(arg1) {
  return window['go']['bindings']['RealtimeRuntimeBinding']['SetContext'](arg1);
}

export function StartProject(arg1, arg2) {
  return window['go']['bindings']['RealtimeRuntimeBinding']['StartProject'](arg1, arg2);
}

export function StartSingleYAML(arg1, arg2) {
  return window['go']['bindings']['RealtimeRuntimeBinding']['StartSingleYAML'](arg1, arg2);
}

export function Stop() {
  return window['go']['bindings']['RealtimeRuntimeBinding']['Stop']();
}
