// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings, realtime, context} from '../models';

export function AckAlarm(arg1:string):Promise<void>;

export function AckAllAlarms():Promise<void>;

export function Cleanup():Promise<void>;

export function DeleteRunHistory(arg1:string):Promise<void>;

export function GetAlarmEvents(arg1:number):Promise<Record<string, any>>;

export function GetAlarms():Promise<Record<string, any>>;

export function GetConnectionInfo():Promise<bindings.RealtimeConnectionInfo>;

export function GetProjectRevision(arg1:string):Promise<string>;

export function GetSession():Promise<realtime.RealtimeRunSession>;

export function ListRunHistory():Promise<Array<Record<string, any>>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartProject(arg1:string,arg2:realtime.RealtimeStartOptions):Promise<realtime.RealtimeRunSession>;

export function StartSingleYAML(arg1:string,arg2:realtime.RealtimeStartOptions):Promise<realtime.RealtimeRunSession>;

export function Stop():Promise<void>;
