// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {realtime} from '../models';
import {context} from '../models';

export function AddSource(arg1:string):Promise<realtime.ProjectView>;

export function CreateProject(arg1:string):Promise<realtime.Project>;

export function DeleteProject(arg1:string):Promise<void>;

export function ListProjects():Promise<Array<realtime.ProjectSummary>>;

export function OpenProject(arg1:string):Promise<realtime.Project>;

export function RemoveSource(arg1:string,arg2:string):Promise<realtime.ProjectView>;

export function RenameProject(arg1:string,arg2:string):Promise<realtime.Project>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateReplicas(arg1:string,arg2:string,arg3:number):Promise<realtime.ProjectView>;

export function ValidateProject(arg1:string):Promise<realtime.ValidationResult>;
