// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1) {
  return window['go']['bindings']['RealtimeProjectBinding']['AddRecentProject'](arg1);
}

export function AddSource(arg1) {
  return window['go']['bindings']['RealtimeProjectBinding']['AddSource'](arg1);
}

export function AddSourceAt(arg1, arg2, arg3) {
  return window['go']['bindings']['RealtimeProjectBinding']['AddSourceAt'](arg1, arg2, arg3);
}

export function ChooseProjectFile() {
  return window['go']['bindings']['RealtimeProjectBinding']['ChooseProjectFile']();
}

export function ChooseSourceYAML() {
  return window['go']['bindings']['RealtimeProjectBinding']['ChooseSourceYAML']();
}

export function ChooseYamlForDsl() {
  return window['go']['bindings']['RealtimeProjectBinding']['ChooseYamlForDsl']();
}

export function ClearAllForces(arg1, arg2) {
  return window['go']['bindings']['RealtimeProjectBinding']['ClearAllForces'](arg1, arg2);
}

export function ClearForce(arg1, arg2, arg3) {
  return window['go']['bindings']['RealtimeProjectBinding']['ClearForce'](arg1, arg2, arg3);
}

export function ClearQuality(arg1, arg2, arg3) {
  return window['go']['bindings']['RealtimeProjectBinding']['ClearQuality'](arg1, arg2, arg3);
}

export function CompileProject(arg1, arg2) {
  return window['go']['bindings']['RealtimeProjectBinding']['CompileProject'](arg1, arg2);
}

export function CreateAlarmRule(arg1, arg2) {
  return window['go']['bindings']['RealtimeProjectBinding']['CreateAlarmRule'](arg1, arg2);
}

export function CreateProject(arg1) {
  return window['go']['bindings']['RealtimeProjectBinding']['CreateProject'](arg1);
}

export function CreateProjectAt(arg1, arg2) {
  return window['go']['bindings']['RealtimeProjectBinding']['CreateProjectAt'](arg1, arg2);
}

export function DeleteAlarmRule(arg1, arg2) {
  return window['go']['bindings']['RealtimeProjectBinding']['DeleteAlarmRule'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['bindings']['RealtimeProjectBinding']['DeleteProject'](arg1);
}

export function GetDashboard(arg1) {
  return window['go']['bindings']['RealtimeProjectBinding']['GetDashboard'](arg1);
}

export function GetForces(arg1, arg2) {
  return window['go']['bindings']['RealtimeProjectBinding']['GetForces'](arg1, arg2);
}

export function GetQualities(arg1, arg2) {
  return window['go']['bindings']['RealtimeProjectBinding']['GetQualities'](arg1, arg2);
}

export function ListAlarmRules(arg1) {
  return window['go']['bindings']['RealtimeProjectBinding']['ListAlarmRules'](arg1);
}

export function ListProjects() {
  return window['go']['bindings']['RealtimeProjectBinding']['ListProjects']();
}

export function ListRecentProjects() {
  return window['go']['bindings']['RealtimeProjectBinding']['ListRecentProjects']();
}

export function OpenProject(arg1) {
  return window['go']['bindings']['RealtimeProjectBinding']['OpenProject'](arg1);
}

export function OpenProjectFile(arg1) {
  return window['go']['bindings']['RealtimeProjectBinding']['OpenProjectFile'](arg1);
}

export function RemoveRecentProject(arg1) {
  return window['go']['bindings']['RealtimeProjectBinding']['RemoveRecentProject'](arg1);
}

export function RemoveSource(arg1, arg2) {
  return window['go']['bindings']['RealtimeProjectBinding']['RemoveSource'](arg1, arg2);
}

export function RemoveSourceAt(arg1, arg2, arg3) {
  return window['go']['bindings']['RealtimeProjectBinding']['RemoveSourceAt'](arg1, arg2, arg3);
}

export function RenameProject(arg1, arg2) {
  return window['go']['bindings']['RealtimeProjectBinding']['RenameProject'](arg1, arg2);
}

export function SaveDashboard(arg1, arg2) {
  return window['go']['bindings']['RealtimeProjectBinding']['SaveDashboard'](arg1, arg2);
}

export function SetCompiler(arg1) {
  return window['go']['bindings']['RealtimeProjectBinding']['SetCompiler'](arg1);
}

export function SetContext(arg1) {
  return window['go']['bindings']['RealtimeProjectBinding']['SetContext'](arg1);
}

export function SetForce(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['bindings']['RealtimeProjectBinding']['SetForce'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetQuality(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['RealtimeProjectBinding']['SetQuality'](arg1, arg2, arg3, arg4);
}

export function SetRuntimeValue(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bindings']['RealtimeProjectBinding']['SetRuntimeValue'](arg1, arg2, arg3, arg4, arg5);
}

export function SetServiceClient(arg1) {
  return window['go']['bindings']['RealtimeProjectBinding']['SetServiceClient'](arg1);
}

export function UpdateAlarmRule(arg1, arg2) {
  return window['go']['bindings']['RealtimeProjectBinding']['UpdateAlarmRule'](arg1, arg2);
}

export function UpdateReplicas(arg1, arg2, arg3) {
  return window['go']['bindings']['RealtimeProjectBinding']['UpdateReplicas'](arg1, arg2, arg3);
}

export function UpdateReplicasAt(arg1, arg2, arg3, arg4) {
  return window['go']['bindings']['RealtimeProjectBinding']['UpdateReplicasAt'](arg1, arg2, arg3, arg4);
}

export function UpdateRuntime(arg1, arg2, arg3) {
  return window['go']['bindings']['RealtimeProjectBinding']['UpdateRuntime'](arg1, arg2, arg3);
}

export function ValidateAlarmRules(arg1) {
  return window['go']['bindings']['RealtimeProjectBinding']['ValidateAlarmRules'](arg1);
}

export function ValidateProject(arg1) {
  return window['go']['bindings']['RealtimeProjectBinding']['ValidateProject'](arg1);
}
