// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {realtime} from '../models';
import {context} from '../models';

export function Cleanup():Promise<void>;

export function GetProjectRevision(arg1:string):Promise<string>;

export function GetSession():Promise<realtime.RealtimeRunSession>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StartProject(arg1:string,arg2:realtime.RealtimeStartOptions):Promise<realtime.RealtimeRunSession>;

export function StartSingleYAML(arg1:string,arg2:realtime.RealtimeStartOptions):Promise<realtime.RealtimeRunSession>;

export function Stop():Promise<void>;
