// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {realtime} from '../models';
import {bindings} from '../models';
import {context} from '../models';

export function AddRecentProject(arg1:string):Promise<void>;

export function AddSource(arg1:string):Promise<realtime.ProjectView>;

export function AddSourceAt(arg1:string,arg2:string,arg3:string):Promise<realtime.OpenedProjectView>;

export function ChooseProjectFile():Promise<string>;

export function ChooseSourceYAML():Promise<string>;

export function ChooseYamlForDsl():Promise<string>;

export function ClearAllForces(arg1:string,arg2:number):Promise<void>;

export function ClearForce(arg1:string,arg2:number,arg3:string):Promise<void>;

export function ClearQuality(arg1:string,arg2:number,arg3:string):Promise<void>;

export function CompileProject(arg1:string,arg2:string):Promise<string>;

export function CreateAlarmRule(arg1:string,arg2:realtime.AlarmRule):Promise<Array<realtime.AlarmRule>>;

export function CreateProject(arg1:string):Promise<realtime.OpenedProject>;

export function CreateProjectAt(arg1:string,arg2:string):Promise<realtime.OpenedProject>;

export function DeleteAlarmRule(arg1:string,arg2:string):Promise<Array<realtime.AlarmRule>>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetDashboard(arg1:string):Promise<realtime.Dashboard>;

export function GetForces(arg1:string,arg2:number):Promise<bindings.ForceState>;

export function GetQualities(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ListAlarmRules(arg1:string):Promise<Array<realtime.AlarmRule>>;

export function ListProjects():Promise<Array<realtime.ProjectSummary>>;

export function ListRecentProjects():Promise<Array<bindings.RecentProjectEntry>>;

export function OpenProject(arg1:string):Promise<realtime.Project>;

export function OpenProjectFile(arg1:string):Promise<realtime.OpenedProject>;

export function RemoveRecentProject(arg1:string):Promise<void>;

export function RemoveSource(arg1:string,arg2:string):Promise<realtime.ProjectView>;

export function RemoveSourceAt(arg1:string,arg2:string,arg3:string):Promise<realtime.OpenedProjectView>;

export function RenameProject(arg1:string,arg2:string):Promise<realtime.Project>;

export function SaveDashboard(arg1:string,arg2:realtime.Dashboard):Promise<realtime.Dashboard>;

export function SetCompiler(arg1:realtime.RealtimeCompiler):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetForce(arg1:string,arg2:number,arg3:string,arg4:string,arg5:any,arg6:any):Promise<void>;

export function SetQuality(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function SetRuntimeValue(arg1:string,arg2:number,arg3:string,arg4:string,arg5:number):Promise<void>;

export function SetServiceClient(arg1:bindings.DataFactoryServiceClient):Promise<void>;

export function UpdateAlarmRule(arg1:string,arg2:realtime.AlarmRule):Promise<Array<realtime.AlarmRule>>;

export function UpdateReplicas(arg1:string,arg2:string,arg3:number):Promise<realtime.ProjectView>;

export function UpdateReplicasAt(arg1:string,arg2:string,arg3:string,arg4:number):Promise<realtime.OpenedProjectView>;

export function UpdateRuntime(arg1:string,arg2:string,arg3:realtime.Runtime):Promise<realtime.OpenedProject>;

export function ValidateAlarmRules(arg1:string):Promise<void>;

export function ValidateProject(arg1:string):Promise<realtime.ValidationResult>;
