// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {context} from '../models';

export function AllocateTempYAMLPath():Promise<string>;

export function BrowseExe():Promise<string>;

export function Cleanup():Promise<void>;

export function CleanupTempYAML(arg1:string):Promise<void>;

export function ExportBatch(arg1:string,arg2:number,arg3:string):Promise<void>;

export function ExportBatchFormatted(arg1:string,arg2:number,arg3:string,arg4:string,arg5:Array<string>,arg6:string):Promise<void>;

export function ExportCSVRows(arg1:Array<string>,arg2:Array<Record<string, any>>,arg3:string):Promise<void>;

export function GetDataFactoryPath():Promise<string>;

export function GetRecentLogs():Promise<Array<string>>;

export function ListConfigs():Promise<Array<string>>;

export function OpenYAMLFile():Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RunBatch(arg1:string,arg2:number):Promise<bindings.BatchResult>;

export function SaveCSVFile():Promise<string>;

export function SaveExportFile(arg1:string):Promise<string>;

export function SaveYAMLFile():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Start(arg1:bindings.StartParams):Promise<void>;

export function Status():Promise<bindings.SystemStatus>;

export function Stop():Promise<void>;

export function WriteTempYAML(arg1:string):Promise<string>;

export function WriteTextFile(arg1:string,arg2:string):Promise<void>;
