// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllocateTempYAMLPath() {
  return window['go']['bindings']['SystemBinding']['AllocateTempYAMLPath']();
}

export function BrowseExe() {
  return window['go']['bindings']['SystemBinding']['BrowseExe']();
}

export function Cleanup() {
  return window['go']['bindings']['SystemBinding']['Cleanup']();
}

export function CleanupTempYAML(arg1) {
  return window['go']['bindings']['SystemBinding']['CleanupTempYAML'](arg1);
}

export function ExportBatch(arg1, arg2, arg3) {
  return window['go']['bindings']['SystemBinding']['ExportBatch'](arg1, arg2, arg3);
}

export function ExportBatchFormatted(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['bindings']['SystemBinding']['ExportBatchFormatted'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ExportCSVRows(arg1, arg2, arg3) {
  return window['go']['bindings']['SystemBinding']['ExportCSVRows'](arg1, arg2, arg3);
}

export function ExportRowsFormatted(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bindings']['SystemBinding']['ExportRowsFormatted'](arg1, arg2, arg3, arg4, arg5);
}

export function GetDataFactoryPath() {
  return window['go']['bindings']['SystemBinding']['GetDataFactoryPath']();
}

export function GetRecentLogs() {
  return window['go']['bindings']['SystemBinding']['GetRecentLogs']();
}

export function ListConfigs() {
  return window['go']['bindings']['SystemBinding']['ListConfigs']();
}

export function OpenYAMLFile() {
  return window['go']['bindings']['SystemBinding']['OpenYAMLFile']();
}

export function ReadTextFile(arg1) {
  return window['go']['bindings']['SystemBinding']['ReadTextFile'](arg1);
}

export function RunBatch(arg1, arg2) {
  return window['go']['bindings']['SystemBinding']['RunBatch'](arg1, arg2);
}

export function SaveCSVFile() {
  return window['go']['bindings']['SystemBinding']['SaveCSVFile']();
}

export function SaveExportFile(arg1) {
  return window['go']['bindings']['SystemBinding']['SaveExportFile'](arg1);
}

export function SaveYAMLFile() {
  return window['go']['bindings']['SystemBinding']['SaveYAMLFile']();
}

export function SetContext(arg1) {
  return window['go']['bindings']['SystemBinding']['SetContext'](arg1);
}

export function Start(arg1) {
  return window['go']['bindings']['SystemBinding']['Start'](arg1);
}

export function Status() {
  return window['go']['bindings']['SystemBinding']['Status']();
}

export function Stop() {
  return window['go']['bindings']['SystemBinding']['Stop']();
}

export function WriteTempYAML(arg1) {
  return window['go']['bindings']['SystemBinding']['WriteTempYAML'](arg1);
}

export function WriteTextFile(arg1, arg2) {
  return window['go']['bindings']['SystemBinding']['WriteTextFile'](arg1, arg2);
}
