// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseExe() {
  return window['go']['bindings']['SystemBinding']['BrowseExe']();
}

export function Cleanup() {
  return window['go']['bindings']['SystemBinding']['Cleanup']();
}

export function ExportBatch(arg1, arg2, arg3) {
  return window['go']['bindings']['SystemBinding']['ExportBatch'](arg1, arg2, arg3);
}

export function GetDataFactoryPath() {
  return window['go']['bindings']['SystemBinding']['GetDataFactoryPath']();
}

export function GetRecentLogs() {
  return window['go']['bindings']['SystemBinding']['GetRecentLogs']();
}

export function ListConfigs() {
  return window['go']['bindings']['SystemBinding']['ListConfigs']();
}

export function OpenYAMLFile() {
  return window['go']['bindings']['SystemBinding']['OpenYAMLFile']();
}

export function RunBatch(arg1, arg2) {
  return window['go']['bindings']['SystemBinding']['RunBatch'](arg1, arg2);
}

export function SaveCSVFile() {
  return window['go']['bindings']['SystemBinding']['SaveCSVFile']();
}

export function SaveYAMLFile() {
  return window['go']['bindings']['SystemBinding']['SaveYAMLFile']();
}

export function SetContext(arg1) {
  return window['go']['bindings']['SystemBinding']['SetContext'](arg1);
}

export function Start(arg1) {
  return window['go']['bindings']['SystemBinding']['Start'](arg1);
}

export function Status() {
  return window['go']['bindings']['SystemBinding']['Status']();
}

export function Stop() {
  return window['go']['bindings']['SystemBinding']['Stop']();
}
