// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {context} from '../models';

export function BrowseExe():Promise<string>;

export function Cleanup():Promise<void>;

export function ExportBatch(arg1:string,arg2:number,arg3:string):Promise<void>;

export function GetDataFactoryPath():Promise<string>;

export function GetRecentLogs():Promise<Array<string>>;

export function ListConfigs():Promise<Array<string>>;

export function OpenYAMLFile():Promise<string>;

export function RunBatch(arg1:string,arg2:number):Promise<bindings.BatchResult>;

export function SaveYAMLFile():Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Start(arg1:bindings.StartParams):Promise<void>;

export function Status():Promise<bindings.SystemStatus>;

export function Stop():Promise<void>;
