// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';

export function IsBuiltinTemplate(arg1:string):Promise<boolean>;

export function LoadBuiltinTemplate():Promise<config.TemplateDocument>;

export function LoadTemplate(arg1:string):Promise<config.TemplateDocument>;

export function SaveTemplate(arg1:config.SaveTemplateRequest):Promise<config.SaveTemplateResult>;

export function ApplyRuntimeOverrides(arg1: {
  targetPath: string
  expectedHash: string
  overrides: Record<string, number>
  includeMV: boolean
}): Promise<{ path: string; contentHash: string; appliedFields: string[] }>;

export function SetContext(arg1:context.Context):Promise<void>;

export function ValidateTemplateConfig(arg1:config.TemplateConfig):Promise<Array<config.ValidationIssue>>;
