// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsBuiltinTemplate(arg1) {
  return window['go']['bindings']['TemplateConfigBinding']['IsBuiltinTemplate'](arg1);
}

export function LoadBuiltinTemplate() {
  return window['go']['bindings']['TemplateConfigBinding']['LoadBuiltinTemplate']();
}

export function LoadTemplate(arg1) {
  return window['go']['bindings']['TemplateConfigBinding']['LoadTemplate'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['bindings']['TemplateConfigBinding']['SaveTemplate'](arg1);
}

export function ApplyRuntimeOverrides(arg1) {
  return window['go']['bindings']['TemplateConfigBinding']['ApplyRuntimeOverrides'](arg1);
}

export function SetContext(arg1) {
  return window['go']['bindings']['TemplateConfigBinding']['SetContext'](arg1);
}

export function ValidateTemplateConfig(arg1) {
  return window['go']['bindings']['TemplateConfigBinding']['ValidateTemplateConfig'](arg1);
}
