// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {config} from '../models';
import {context} from '../models';

export function ApplyRuntimeOverrides(arg1:bindings.ApplyRuntimeOverridesRequest):Promise<bindings.ApplyRuntimeOverridesResult>;

export function IsBuiltinTemplate(arg1:string):Promise<boolean>;

export function LoadBuiltinTemplate():Promise<config.TemplateDocument>;

export function LoadTemplate(arg1:string):Promise<config.TemplateDocument>;

export function SaveTemplate(arg1:config.SaveTemplateRequest):Promise<config.SaveTemplateResult>;

export function SetContext(arg1:context.Context):Promise<void>;

export function ValidateTemplateConfig(arg1:config.TemplateConfig):Promise<Array<config.ValidationIssue>>;
