// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetEnvStatus() {
  return window['go']['bindings']['EnvBinding']['GetEnvStatus']();
}

export function GetMockerConfig() {
  return window['go']['bindings']['EnvBinding']['GetMockerConfig']();
}

export function KillPort(arg1) {
  return window['go']['bindings']['EnvBinding']['KillPort'](arg1);
}

export function SetMockerConfig(arg1) {
  return window['go']['bindings']['EnvBinding']['SetMockerConfig'](arg1);
}
