// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {env} from '../models';
import {mock} from '../models';
import {bindings} from '../models';

export function GetEnvStatus():Promise<env.EnvStatus>;

export function GetMockerConfig():Promise<mock.MockerConfigResult>;

export function KillPort(arg1:number):Promise<bindings.KillPortResult>;

export function SetMockerConfig(arg1:bindings.SetMockerConfigRequest):Promise<mock.MockerConfigResult>;
