// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bindings} from '../models';
import {verify} from '../models';

export function GetRunDetail(arg1:number):Promise<bindings.RunDetailResponse>;

export function ListRuns():Promise<Array<verify.RunRecord>>;
