// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRunDetail(arg1) {
  return window['go']['bindings']['HistoryBinding']['GetRunDetail'](arg1);
}

export function ListRuns() {
  return window['go']['bindings']['HistoryBinding']['ListRuns']();
}
