// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPerformanceParams() {
  return window['go']['bindings']['MockBinding']['GetPerformanceParams']();
}

export function ListMocks() {
  return window['go']['bindings']['MockBinding']['ListMocks']();
}

export function SetPerformanceParams(arg1) {
  return window['go']['bindings']['MockBinding']['SetPerformanceParams'](arg1);
}

export function StartAllMocks() {
  return window['go']['bindings']['MockBinding']['StartAllMocks']();
}

export function StartMock(arg1) {
  return window['go']['bindings']['MockBinding']['StartMock'](arg1);
}

export function StopAllMocks() {
  return window['go']['bindings']['MockBinding']['StopAllMocks']();
}

export function StopMock(arg1) {
  return window['go']['bindings']['MockBinding']['StopMock'](arg1);
}
