// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mock} from '../models';
import {bindings} from '../models';

export function GetPerformanceParams():Promise<mock.PerfParams>;

export function ListMocks():Promise<Array<mock.MockSummary>>;

export function SetPerformanceParams(arg1:mock.PerfParams):Promise<mock.PerfParams>;

export function StartAllMocks():Promise<bindings.StartAllResult>;

export function StartMock(arg1:string):Promise<mock.MockRuntime>;

export function StopAllMocks():Promise<bindings.StopAllResult>;

export function StopMock(arg1:string):Promise<bindings.MockStopResult>;
