// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {provision} from '../models';
import {subject} from '../models';

export function AddDataSource(arg1:provision.AddDataSourceRequest):Promise<subject.DsInfo>;

export function AddMissingTags(arg1:provision.AddMissingTagsRequest):Promise<Array<string>>;

export function ChangeDsState(arg1:provision.ChangeDsStateRequest):Promise<void>;

export function DeleteAllTags(arg1:provision.DeleteAllTagsRequest):Promise<void>;

export function DeleteDataSource(arg1:provision.DeleteDataSourceRequest):Promise<void>;

export function DeleteDuplicateTags(arg1:provision.DeleteDuplicateTagsRequest):Promise<void>;

export function GetHeartbeatValue(arg1:provision.GetHeartbeatValueRequest):Promise<provision.HeartbeatValue>;

export function GetProvisionState(arg1:provision.ProvisionStateRequest):Promise<provision.ProvisionState>;

export function Provision(arg1:provision.ProvisionRequest):Promise<provision.DsProvisionResult>;

export function RebuildDataSource(arg1:provision.RebuildDataSourceRequest):Promise<provision.DsProvisionResult>;
