// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDataSource(arg1) {
  return window['go']['bindings']['ProvisionBinding']['AddDataSource'](arg1);
}

export function AddMissingTags(arg1) {
  return window['go']['bindings']['ProvisionBinding']['AddMissingTags'](arg1);
}

export function ChangeDsState(arg1) {
  return window['go']['bindings']['ProvisionBinding']['ChangeDsState'](arg1);
}

export function DeleteAllTags(arg1) {
  return window['go']['bindings']['ProvisionBinding']['DeleteAllTags'](arg1);
}

export function DeleteDataSource(arg1) {
  return window['go']['bindings']['ProvisionBinding']['DeleteDataSource'](arg1);
}

export function DeleteDuplicateTags(arg1) {
  return window['go']['bindings']['ProvisionBinding']['DeleteDuplicateTags'](arg1);
}

export function GetHeartbeatValue(arg1) {
  return window['go']['bindings']['ProvisionBinding']['GetHeartbeatValue'](arg1);
}

export function GetProvisionState(arg1) {
  return window['go']['bindings']['ProvisionBinding']['GetProvisionState'](arg1);
}

export function Provision(arg1) {
  return window['go']['bindings']['ProvisionBinding']['Provision'](arg1);
}

export function RebuildDataSource(arg1) {
  return window['go']['bindings']['ProvisionBinding']['RebuildDataSource'](arg1);
}
