// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {verify} from '../models';

export function RunVerification(arg1:verify.VerifyRequest):Promise<verify.VerifyRunResult>;
