// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunVerification(arg1) {
  return window['go']['bindings']['VerifyBinding']['RunVerification'](arg1);
}
