// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';
import {model} from '../models';
import {collector} from '../models';

export function AckAlert(arg1:number):Promise<boolean>;

export function AddCluster(arg1:config.ClusterConfig):Promise<main.SaveConfigResult>;

export function CountAlerts(arg1:string):Promise<number>;

export function GetActorEvents(arg1:string,arg2:main.HistoryRange):Promise<Array<model.ActorEvent>>;

export function GetActors(arg1:string):Promise<Array<model.ActorSnapshot>>;

export function GetClusterStatus(arg1:string):Promise<model.CollectorStatus>;

export function GetConfig():Promise<config.Config>;

export function GetDBPath():Promise<string>;

export function GetGlobalPerf():Promise<model.GlobalPerf>;

export function GetJobHistory(arg1:string,arg2:main.HistoryRange,arg3:string):Promise<Array<model.JobSnapshot>>;

export function GetJobs(arg1:string):Promise<Array<model.JobSnapshot>>;

export function GetLogPath():Promise<string>;

export function GetNodeHistory(arg1:string,arg2:string,arg3:main.HistoryRange):Promise<Array<model.NodeMetric>>;

export function GetNodes(arg1:string):Promise<Array<model.NodeMetric>>;

export function GetPerf(arg1:string):Promise<model.PerfMetrics>;

export function GetSnapshot(arg1:string):Promise<collector.Snapshot>;

export function GetWorkers(arg1:string):Promise<Array<model.WorkerSnapshot>>;

export function ListAlerts(arg1:string):Promise<Array<model.Alert>>;

export function ListClusterIDs():Promise<Array<string>>;

export function OpenInFolder(arg1:string):Promise<void>;

export function RemoveCluster(arg1:string):Promise<main.SaveConfigResult>;

export function SaveConfig(arg1:config.Config):Promise<main.SaveConfigResult>;

export function StartAll():Promise<void>;

export function StartCluster(arg1:string):Promise<void>;

export function StopAll():Promise<void>;

export function StopCluster(arg1:string):Promise<void>;

export function UpdateCluster(arg1:config.ClusterConfig):Promise<main.SaveConfigResult>;
