// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckAlert(arg1) {
  return window['go']['main']['App']['AckAlert'](arg1);
}

export function AddCluster(arg1) {
  return window['go']['main']['App']['AddCluster'](arg1);
}

export function CountAlerts(arg1) {
  return window['go']['main']['App']['CountAlerts'](arg1);
}

export function GetActorEvents(arg1, arg2) {
  return window['go']['main']['App']['GetActorEvents'](arg1, arg2);
}

export function GetActors(arg1) {
  return window['go']['main']['App']['GetActors'](arg1);
}

export function GetClusterStatus(arg1) {
  return window['go']['main']['App']['GetClusterStatus'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDBPath() {
  return window['go']['main']['App']['GetDBPath']();
}

export function GetGlobalPerf() {
  return window['go']['main']['App']['GetGlobalPerf']();
}

export function GetJobHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetJobHistory'](arg1, arg2, arg3);
}

export function GetJobs(arg1) {
  return window['go']['main']['App']['GetJobs'](arg1);
}

export function GetLogPath() {
  return window['go']['main']['App']['GetLogPath']();
}

export function GetNodeHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetNodeHistory'](arg1, arg2, arg3);
}

export function GetNodes(arg1) {
  return window['go']['main']['App']['GetNodes'](arg1);
}

export function GetPerf(arg1) {
  return window['go']['main']['App']['GetPerf'](arg1);
}

export function GetSnapshot(arg1) {
  return window['go']['main']['App']['GetSnapshot'](arg1);
}

export function GetWorkers(arg1) {
  return window['go']['main']['App']['GetWorkers'](arg1);
}

export function ListAlerts(arg1) {
  return window['go']['main']['App']['ListAlerts'](arg1);
}

export function ListClusterIDs() {
  return window['go']['main']['App']['ListClusterIDs']();
}

export function OpenInFolder(arg1) {
  return window['go']['main']['App']['OpenInFolder'](arg1);
}

export function RemoveCluster(arg1) {
  return window['go']['main']['App']['RemoveCluster'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartAll() {
  return window['go']['main']['App']['StartAll']();
}

export function StartCluster(arg1) {
  return window['go']['main']['App']['StartCluster'](arg1);
}

export function StopAll() {
  return window['go']['main']['App']['StopAll']();
}

export function StopCluster(arg1) {
  return window['go']['main']['App']['StopCluster'](arg1);
}

export function UpdateCluster(arg1) {
  return window['go']['main']['App']['UpdateCluster'](arg1);
}
