// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['bindings']['DebugBinding']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['bindings']['DebugBinding']['Disconnect']();
}

export function ExportCsv(arg1) {
  return window['go']['bindings']['DebugBinding']['ExportCsv'](arg1);
}

export function GetDisplayVariables() {
  return window['go']['bindings']['DebugBinding']['GetDisplayVariables']();
}

export function GetLastSnapshot() {
  return window['go']['bindings']['DebugBinding']['GetLastSnapshot']();
}

export function GetMeta() {
  return window['go']['bindings']['DebugBinding']['GetMeta']();
}

export function GetSnapshotHistory() {
  return window['go']['bindings']['DebugBinding']['GetSnapshotHistory']();
}

export function GetStatus() {
  return window['go']['bindings']['DebugBinding']['GetStatus']();
}

export function IsConnected() {
  return window['go']['bindings']['DebugBinding']['IsConnected']();
}

export function Override(arg1, arg2) {
  return window['go']['bindings']['DebugBinding']['Override'](arg1, arg2);
}

export function SetParam(arg1, arg2, arg3) {
  return window['go']['bindings']['DebugBinding']['SetParam'](arg1, arg2, arg3);
}
