// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string):Promise<string>;

export function Disconnect():Promise<void>;

export function ExportCsv(arg1:string):Promise<string>;

export function GetDisplayVariables():Promise<string>;

export function GetLastSnapshot():Promise<string>;

export function GetMeta():Promise<string>;

export function GetSnapshotHistory():Promise<string>;

export function GetStatus():Promise<string>;

export function IsConnected():Promise<boolean>;

export function Override(arg1:string,arg2:number):Promise<void>;

export function SetParam(arg1:string,arg2:string,arg3:number):Promise<void>;
