// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompareAlgorithms(arg1) {
  return window['go']['main']['App']['CompareAlgorithms'](arg1);
}

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function ExportAlgorithms(arg1) {
  return window['go']['main']['App']['ExportAlgorithms'](arg1);
}

export function GetPublishedAlgorithms() {
  return window['go']['main']['App']['GetPublishedAlgorithms']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function LoadCSVFile(arg1) {
  return window['go']['main']['App']['LoadCSVFile'](arg1);
}

export function PickCSVFile() {
  return window['go']['main']['App']['PickCSVFile']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function SaveCSVFile(arg1) {
  return window['go']['main']['App']['SaveCSVFile'](arg1);
}

export function StartPublish(arg1, arg2) {
  return window['go']['main']['App']['StartPublish'](arg1, arg2);
}

export function StartRepublish() {
  return window['go']['main']['App']['StartRepublish']();
}

export function StartSync(arg1, arg2) {
  return window['go']['main']['App']['StartSync'](arg1, arg2);
}
