program:
  - name: sin1
    type: SINE_WAVE
    params:
      amplitude: 100.0
      period: 1200
      phase: 0.0
    display_args: ["out[100]"]

  - name: lagging_sin1
    type: Lag
    source: sin1.out
    delay: 30
    display_args: ["lagging_sin1[100]"]

  - name: non_sense_1
    type: RANDOM
    params:
      L: 0.0
      H: 100.0
      max_step: 3.0
    display_args: ["out[100]"]

  - name: non_sense_2
    type: RANDOM
    params:
      L: 0.0
      H: 100.0
      max_step: 3.0
    display_args: ["out[100]"]

  - name: non_sense_3
    type: Expression
    formula: non_sense_1[-30] + 2 * non_sense_2
    display_args: ["non_sense_3[200]"]

  - name: non_sense_4
    type: Expression
    formula: sin(non_sense_3)
    display_args: ["non_sense_4[2]"]
