// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchCreateUsers(arg1, arg2) {
  return window['go']['main']['App']['BatchCreateUsers'](arg1, arg2);
}

export function CancelBatch(arg1) {
  return window['go']['main']['App']['CancelBatch'](arg1);
}

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DownloadBatchTemplate() {
  return window['go']['main']['App']['DownloadBatchTemplate']();
}

export function GetAllUsers(arg1) {
  return window['go']['main']['App']['GetAllUsers'](arg1);
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}

export function ListUsers(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListUsers'](arg1, arg2, arg3);
}

export function LoadLoginConfig() {
  return window['go']['main']['App']['LoadLoginConfig']();
}

export function Login(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3, arg4);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function ParseExcelFile(arg1) {
  return window['go']['main']['App']['ParseExcelFile'](arg1);
}

export function PickExcelFile() {
  return window['go']['main']['App']['PickExcelFile']();
}

export function ResetPassword(arg1, arg2) {
  return window['go']['main']['App']['ResetPassword'](arg1, arg2);
}

export function SaveLoginConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveLoginConfig'](arg1, arg2);
}
