// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {excel} from '../models';

export function BatchCreateUsers(arg1:Array<api.UserDraft>,arg2:number):Promise<string>;

export function CancelBatch(arg1:string):Promise<boolean>;

export function CreateUser(arg1:api.UserDraft):Promise<api.OperationStatus>;

export function DownloadBatchTemplate():Promise<string>;

export function GetAllUsers(arg1:string):Promise<Array<api.User>>;

export function IsLoggedIn():Promise<boolean>;

export function ListUsers(arg1:number,arg2:number,arg3:string):Promise<api.PageResponse>;

export function LoadLoginConfig():Promise<api.LoginConfig>;

export function Login(arg1:string,arg2:string,arg3:string,arg4:string):Promise<api.OperationStatus>;

export function Logout():Promise<boolean>;

export function ParseExcelFile(arg1:string):Promise<excel.ParseResult>;

export function PickExcelFile():Promise<string>;

export function ResetPassword(arg1:number,arg2:string):Promise<api.OperationStatus>;

export function SaveLoginConfig(arg1:string,arg2:string):Promise<boolean>;
